### ISSUE TITLE
Improve error messaging to user

### ISSUE THREAD

**Issue by jackparmer** [plotly/spectacle-editor#165]
I can upload this presentation at https://plot.ly/organize/

But it does not seem to upload through SpecEd:

![image](https://cloud.githubusercontent.com/assets/1865834/18056773/57ddd6a4-6ddb-11e6-947a-4e438af988a6.png)

I couldn't open Dev Tools through Alt-Ctrl-i, so I don't have much insight into why this might be 😞 

My only guess is that this presentation is much larger than other ones that I've successfully uploaded through SpecEd (12 MB).

In any case, it would be great to have an error message if the upload fails, or some type of status indicator that the upload is occurring for large files. 

Here is how the presentation looks on Plotly:

https://plot.ly/~jackp/16661 

[aircheck.json.zip](https://github.com/FormidableLabs/spectacle-editor/files/442714/aircheck.json.zip)

**Comment by bmathews** [comment]
The response from the API POST is `413`:
`POST https://api.plot.ly/v2/spectacle-presentations 413 (REQUEST ENTITY TOO LARGE)`

This would likely need to be a server/api configuration change.

**Comment by mdtusz** [comment]
Yep - this is on our end. @tarzzz can we change this to something a little bigger? I imagine a large part of their size is the encoded thumbnails?

**Comment by scjody** [comment]
We'll increase the limit, but note that this is also a Spectacle issue.  They need to check if their requests are successful, because all sorts of things could go wrong (user hits a limit in their Plotly account, user isn't signed in to Plotly correctly, user's Internet connection is terrible, etc...)

**Comment by coopy** [comment]
Suggested Spectacle fix: Error message should be consistent with the cause of the error.
